<a href="https://colab.research.google.com/github/worm2007/LexiBrief/blob/main/jupyterprojects.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Using Jupyter Notebooks
:label:`sec_jupyter`


This section describes how to edit and run the code
in each section of this book
using the Jupyter Notebook. Make sure you have
installed Jupyter and downloaded the
code as described in
:ref:`chap_installation`.
If you want to know more about Jupyter see the excellent tutorial in
their [documentation](https://jupyter.readthedocs.io/en/latest/).


## Editing and Running the Code Locally

Suppose that the local path of the book's code is `xx/yy/d2l-en/`. Use the shell to change the directory to this path (`cd xx/yy/d2l-en`) and run the command `jupyter notebook`. If your browser does not do this automatically, open http://localhost:8888 and you will see the interface of Jupyter and all the folders containing the code of the book, as shown in :numref:`fig_jupyter00`.

![The folders containing the code of this book.](https://github.com/d2l-ai/d2l-en-colab/blob/master/img/jupyter00.png?raw=1)
:width:`600px`
:label:`fig_jupyter00`


You can access the notebook files by clicking on the folder displayed on the webpage.
They usually have the suffix ".ipynb".
For the sake of brevity, we create a temporary "test.ipynb" file.
The content displayed after you click it is
shown in :numref:`fig_jupyter01`.
This notebook includes a markdown cell and a code cell. The content in the markdown cell includes "This Is a Title" and "This is text.".
The code cell contains two lines of Python code.

![Markdown and code cells in the "text.ipynb" file.](https://github.com/d2l-ai/d2l-en-colab/blob/master/img/jupyter01.png?raw=1)
:width:`600px`
:label:`fig_jupyter01`


Double click on the markdown cell to enter edit mode.
Add a new text string "Hello world." at the end of the cell, as shown in :numref:`fig_jupyter02`.

![Edit the markdown cell.](https://github.com/d2l-ai/d2l-en-colab/blob/master/img/jupyter02.png?raw=1)
:width:`600px`
:label:`fig_jupyter02`


As demonstrated in :numref:`fig_jupyter03`,
click "Cell" $\rightarrow$ "Run Cells" in the menu bar to run the edited cell.

![Run the cell.](https://github.com/d2l-ai/d2l-en-colab/blob/master/img/jupyter03.png?raw=1)
:width:`600px`
:label:`fig_jupyter03`

After running, the markdown cell is shown in :numref:`fig_jupyter04`.

![The markdown cell after running.](https://github.com/d2l-ai/d2l-en-colab/blob/master/img/jupyter04.png?raw=1)
:width:`600px`
:label:`fig_jupyter04`


Next, click on the code cell. Multiply the elements by 2 after the last line of code, as shown in :numref:`fig_jupyter05`.

![Edit the code cell.](https://github.com/d2l-ai/d2l-en-colab/blob/master/img/jupyter05.png?raw=1)
:width:`600px`
:label:`fig_jupyter05`


You can also run the cell with a shortcut ("Ctrl + Enter" by default) and obtain the output result from :numref:`fig_jupyter06`.

![Run the code cell to obtain the output.](https://github.com/d2l-ai/d2l-en-colab/blob/master/img/jupyter06.png?raw=1)
:width:`600px`
:label:`fig_jupyter06`


When a notebook contains more cells, we can click "Kernel" $\rightarrow$ "Restart & Run All" in the menu bar to run all the cells in the entire notebook. By clicking "Help" $\rightarrow$ "Edit Keyboard Shortcuts" in the menu bar, you can edit the shortcuts according to your preferences.

## Advanced Options

Beyond local editing two things are quite important: editing the notebooks in the markdown format and running Jupyter remotely.
The latter matters when we want to run the code on a faster server.
The former matters since Jupyter's native ipynb format stores a lot of auxiliary data that is
irrelevant to the content,
mostly related to how and where the code is run.
This is confusing for Git, making
reviewing contributions very difficult.
Fortunately there is an alternative---native editing in the markdown format.

### Markdown Files in Jupyter

If you wish to contribute to the content of this book, you need to modify the
source file (md file, not ipynb file) on GitHub.
Using the notedown plugin we
can modify notebooks in the md format directly in Jupyter.


First, install the notedown plugin, run the Jupyter Notebook, and load the plugin:

```
pip install d2l-notedown  # You may need to uninstall the original notedown.
jupyter notebook --NotebookApp.contents_manager_class='notedown.NotedownContentsManager'
```

You may also turn on the notedown plugin by default whenever you run the Jupyter Notebook.
First, generate a Jupyter Notebook configuration file (if it has already been generated, you can skip this step).

```
jupyter notebook --generate-config
```

Then, add the following line to the end of the Jupyter Notebook configuration file (for Linux or macOS, usually in the path `~/.jupyter/jupyter_notebook_config.py`):

```
c.NotebookApp.contents_manager_class = 'notedown.NotedownContentsManager'
```

After that, you only need to run the `jupyter notebook` command to turn on the notedown plugin by default.

### Running Jupyter Notebooks on a Remote Server

Sometimes, you may want to run Jupyter notebooks on a remote server and access it through a browser on your local computer. If Linux or macOS is installed on your local machine (Windows can also support this function through third-party software such as PuTTY), you can use port forwarding:

```
ssh myserver -L 8888:localhost:8888
```

The above string `myserver` is the address of the remote server.
Then we can use http://localhost:8888 to access the remote server `myserver` that runs Jupyter notebooks. We will detail on how to run Jupyter notebooks on AWS instances
later in this appendix.

### Timing

We can use the `ExecuteTime` plugin to time the execution of each code cell in Jupyter notebooks.
Use the following commands to install the plugin:

```
pip install jupyter_contrib_nbextensions
jupyter contrib nbextension install --user
jupyter nbextension enable execute_time/ExecuteTime
```

## Summary

* Using the Jupyter Notebook tool, we can edit, run, and contribute to each section of the book.
* We can run Jupyter notebooks on remote servers using port forwarding.


## Exercises

1. Edit and run the code in this book with the Jupyter Notebook on your local machine.
1. Edit and run the code in this book with the Jupyter Notebook *remotely* via port forwarding.
1. Compare the running time of the operations $\mathbf{A}^\top \mathbf{B}$ and $\mathbf{A} \mathbf{B}$ for two square matrices in $\mathbb{R}^{1024 \times 1024}$. Which one is faster?


[Discussions](https://discuss.d2l.ai/t/421)


In [ ]:
age=40
if age>=18 and age<60:
  print("eligible")
else:
    print("not eligible")

eligible


In [ ]:
marks=int(input("Enter your marks here:"));
rank=int(input("Enter your rank here:"));
if marks>18 and rank<600000:
    print("Eligible")
else:
    print("not eligible")

Enter your marks here:5090
Enter your rank here:45567
Eligible


In [ ]:
age=int(input("Enter your age here:"));
if age>60:
    print("Senior Citizen")
elif age<=60 and age>35:
    print("Middle age")
elif age<=35 and age>18:
    print("Young Adult")
else:
    print("Kids")

Enter your age here:56
Middle age


In [ ]:
marks=int(input("Enter your marks:"))
if marks>90:
  print("Grade A")
elif marks>80:
  print("Grade B")
elif marks>70:
  print("Grade C")
elif marks>60:
  print("Grade D")
elif marks>50:
  print("Grade E")
else:
  print("Fail")

Enter your marks:82
Grade B


In [ ]:
num=int(input("Enter a number:"))
if num%5==0:
  print("divisible")
else:
  print("not divisible")

Enter a number:453
not divisible


In [ ]:
num=int(input("Enter a number:"))
if num%3==0:
  print("divisible")
else:
  print("not divisible")

Enter a number:67
not divisible


In [ ]:
num=int(input("Enter a number:"))
if num%3==0 and num%5==0:
  print("divisible by both 3 and 5")
elif num%3==0:
  print("divisible by 3")
elif num%5==0:
  print("divisible by 5")
else:
  print("not divisible")

Enter a number:35
divisible by 5


In [ ]:
bal=int(input("Enter your balance:"))
dem=int(input("Enter the amount to be withdrawn"))
if dem<=bal:
  print("can be withdrawn")
else:
  print("cannot be withdrawn")


Enter your balance:800
Enter the amount to be withdrawn900
cannot be withdrawn


In [ ]:
pas=int(input("Enter your password:"))
amt=int(input("Enter the amount to be withdrawn"))
p=1234
if pas==p:
  print("amount can be withfrawn")
else:
  print("incorrect password")

Enter your password:123
Enter the amount to be withdrawn21
incorrect password


In [ ]:
num=int(input("Enter a number:"))
if num>=9 and num<100 or num>-99 and num<-9:
  print("two digit number")
elif num>=0 and num<=9 or num>=-9 and num<=-1:
  print("single digit number")
else:
  print("more than two digit number")

Enter a number:-9
single digit number


In [ ]:
for i in range(50,4,-5):
    print(i)

50
45
40
35
30
25
20
15
10
5


In [ ]:
num1 = int(input("Enter the first number: "))
operator = input("Enter an operator (+, -, *, /): ")
num2 = int(input("Enter the second number: "))

if operator == '+':
    result = num1 + num2
elif operator == '-':
    result = num1 - num2
elif operator == '*':
    result = num1 * num2
elif operator == '/':
    result = num1 / num2
else:
    result = "Error: Invalid operator"

print("Result: ", result)

Enter the first number: 2
Enter an operator (+, -, *, /): +3
Enter the second number: 9
Result:  Error: Invalid operator


In [ ]:
name="I Love to read books"
print(name[0:2])
# [start:end:step]  # For reversing
print(name[::-1])

In [ ]:
name="Harshit"
print("Harshit"*5)

In [ ]:
name="Anubhav Tiwari"
print(name+"_"+title)
print("u" in name)
print(name.upper())
print(name.lower())
print(name.title())
print(name.split())
print(name.replace("Anubhav", "Tiwari"))
print(name.capitalize())

In [ ]:
name="Anubhav Tiwari"
print(name.split())
print(name.find("a"))
print(name.count("a"))
print(len(name))

In [ ]:
a=[10,20,30]
b=[20,30]
print(a+b)
print(a[0])
print([10,20]*30)
print(a[0:2])
print(20 in[10,20,30])

In [ ]:
a.extend([40,50])
print(a)

In [ ]:
a=[30,10,20,50,60]
a.sort()
print(a)
print(a.index(30))
a.reverse()
print(a)
a.clear()
print(a)
print(a.count(20))

[10, 20, 30, 50, 60]
2
[60, 50, 30, 20, 10]
[]
0


In [ ]:
import pandas as pd
marks = pd.Series([85,90,78,95])
print(marks)

0    85
1    90
2    78
3    95
dtype: int64


In [ ]:
student={
    "Name":["Rahul","Amit","Priya"],
    "Age":[20,21,19],
    "Marks":[80,90,95],
}
df=pd.DataFrame(student)
print(df)

NameError: name 'pd' is not defined

In [ ]:
df=pd.read_csv('/Zomato-data-.csv')


In [ ]:
df.to_csv("output.csv")

In [ ]:
df.head()

In [ ]:
df.head(10)

In [ ]:
df.tail(55)

In [ ]:
df.sample(5)

In [ ]:
df.shape

(148, 7)

In [ ]:
df.columns

Index(['name', 'online_order', 'book_table', 'rate', 'votes',
       'approx_cost(for two people)', 'listed_in(type)'],
      dtype='object')

In [ ]:
df.dtypes

,0
name,object
online_order,object
book_table,object
rate,object
votes,int64
approx_cost(for two people),int64
listed_in(type),object


In [ ]:
df.info()

NameError: name 'df' is not defined

In [ ]:
df['approx_cost(for two people)'].describe()

In [ ]:
df["name"]

In [ ]:
df.sort_values("approx_cost(for two people)")


In [ ]:
df.sort_values("approx_cost(for two people)",ascending=False)

In [ ]:
import pandas as pd

data = {
    "Emp_ID": [101,102,103,104,105,106,107,108,109,110],
    "Name": ["Aman","Neha","Rahul","Priya","Karan",
             "Simran","Mohit","Anjali","Vikas","Pooja"],
    "Age": [24,25,23,28,30,26,27,24,29,25],
    "Department": ["HR","IT","Sales","IT","HR",
                   "Finance","Sales","IT","Finance","HR"],
    "Salary": [35000,50000,45000,60000,38000,
               55000,47000,62000,58000,40000],
    "City": ["Delhi","Lucknow","Noida","Delhi","Jaipur",
             "Noida","Lucknow","Delhi","Jaipur","Delhi"]
}

df = pd.DataFrame(data)

print(df)

   Emp_ID    Name  Age Department  Salary     City
0     101    Aman   24         HR   35000    Delhi
1     102    Neha   25         IT   50000  Lucknow
2     103   Rahul   23      Sales   45000    Noida
3     104   Priya   28         IT   60000    Delhi
4     105   Karan   30         HR   38000   Jaipur
5     106  Simran   26    Finance   55000    Noida
6     107   Mohit   27      Sales   47000  Lucknow
7     108  Anjali   24         IT   62000    Delhi
8     109   Vikas   29    Finance   58000   Jaipur
9     110   Pooja   25         HR   40000    Delhi


In [ ]:
df.head()


,Emp_ID,Name,Age,Department,Salary,City
0,101,Aman,24,HR,35000,Delhi
1,102,Neha,25,IT,50000,Lucknow
2,103,Rahul,23,Sales,45000,Noida
3,104,Priya,28,IT,60000,Delhi
4,105,Karan,30,HR,38000,Jaipur


In [ ]:
df.tail()


,Emp_ID,Name,Age,Department,Salary,City
5,106,Simran,26,Finance,55000,Noida
6,107,Mohit,27,Sales,47000,Lucknow
7,108,Anjali,24,IT,62000,Delhi
8,109,Vikas,29,Finance,58000,Jaipur
9,110,Pooja,25,HR,40000,Delhi


In [ ]:
df.sample()

,Emp_ID,Name,Age,Department,Salary,City
7,108,Anjali,24,IT,62000,Delhi


In [ ]:
df.shape

(10, 6)

In [ ]:
df.columns


Index(['Emp_ID', 'Name', 'Age', 'Department', 'Salary', 'City'], dtype='object')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   Emp_ID      10 non-null     int64 
 1   Name        10 non-null     object
 2   Age         10 non-null     int64 
 3   Department  10 non-null     object
 4   Salary      10 non-null     int64 
 5   City        10 non-null     object
dtypes: int64(3), object(3)
memory usage: 612.0+ bytes


In [ ]:
df.describe()

In [ ]:
df.dtypes

In [ ]:
df["Name"]

,Name
0,Aman
1,Neha
2,Rahul
3,Priya
4,Karan
5,Simran
6,Mohit
7,Anjali
8,Vikas
9,Pooja


In [ ]:
df[["Name", "Salary"]]

,Name,Salary
0,Aman,35000
1,Neha,50000
2,Rahul,45000
3,Priya,60000
4,Karan,38000
5,Simran,55000
6,Mohit,47000
7,Anjali,62000
8,Vikas,58000
9,Pooja,40000


In [ ]:
df["Name"].unique()

array(['Aman', 'Neha', 'Rahul', 'Priya', 'Karan', 'Simran', 'Mohit',
       'Anjali', 'Vikas', 'Pooja'], dtype=object)

In [ ]:
df[df["Salary"]>50000]

,Emp_ID,Name,Age,Department,Salary,City
3,104,Priya,28,IT,60000,Delhi
5,106,Simran,26,Finance,55000,Noida
7,108,Anjali,24,IT,62000,Delhi
8,109,Vikas,29,Finance,58000,Jaipur


In [ ]:
df[df["Department"] == "IT"]

,Emp_ID,Name,Age,Department,Salary,City
1,102,Neha,25,IT,50000,Lucknow
3,104,Priya,28,IT,60000,Delhi
7,108,Anjali,24,IT,62000,Delhi


In [ ]:
df.sort_values("Salary",ascending=False)


,Emp_ID,Name,Age,Department,Salary,City
7,108,Anjali,24,IT,62000,Delhi
3,104,Priya,28,IT,60000,Delhi
8,109,Vikas,29,Finance,58000,Jaipur
5,106,Simran,26,Finance,55000,Noida
1,102,Neha,25,IT,50000,Lucknow
6,107,Mohit,27,Sales,47000,Lucknow
2,103,Rahul,23,Sales,45000,Noida
9,110,Pooja,25,HR,40000,Delhi
4,105,Karan,30,HR,38000,Jaipur
0,101,Aman,24,HR,35000,Delhi


In [ ]:
df["Salary"].mean()

np.float64(49000.0)

In [ ]:
df["Salary"].max()

62000

In [ ]:
df["Salary"].min()

35000

In [ ]:
df["Salary"].sum()

np.int64(490000)

In [ ]:
df["Name"].count()

np.int64(10)

In [ ]:
df["Department"].unique()

array(['HR', 'IT', 'Sales', 'Finance'], dtype=object)

In [ ]:
df["Department"].nunique()

4

In [ ]:
df["Bonus"]=df["Salary"]*0.5

In [ ]:
df.rename(columns={"Name": "Emp_Name"}, inplace=True)
print(df)

In [ ]:
df.drop("Bonus",axis=1,inplace=True)
print(df)

In [ ]:
df.isnull()

In [ ]:
df.isnull().sum()

,0
Emp_ID,0
Emp_Name,0
Age,0
Department,0
Salary,0
City,0


In [ ]:
df.duplicated()

,0
0,False
1,False
2,False
3,False
4,False
5,False
6,False
7,False
8,False
9,False


In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
import pandas as pd

data = {
    "Student_ID": [101,102,103,104,105,106,107,108,109,110,
                   111,112,113,114,115,116,117,118,119,120],

    "Name": ["Aman","Neha","Rahul","Priya","Karan",
             "Simran","Mohit","Anjali","Vikas","Pooja",
             "Rohit","Sneha","Arjun","Riya","Deepak",
             "Muskan","Yash","Komal","Abhishek","Nisha"],

    "Gender": ["Male","Female","Male","Female","Male",
               "Female","Male","Female","Male","Female",
               "Male","Female","Male","Female","Male",
               "Female","Male","Female","Male","Female"],

    "Age": [20,21,19,22,20,21,20,19,22,20,
            21,20,23,19,22,20,21,22,20,19],

    "Department": ["CSE","IT","ECE","CSE","IT",
                   "CSE","ECE","IT","CSE","ECE",
                   "IT","CSE","ECE","IT","CSE",
                   "ECE","IT","CSE","ECE","IT"],

    "Semester": [4,4,2,6,4,6,2,4,8,6,
                 2,8,6,4,8,2,6,4,8,2],

    "Marks": [85,92,78,95,67,88,72,91,81,76,
              69,94,73,89,97,66,82,90,79,84],

    "Attendance": [92,95,85,97,78,90,82,98,88,84,
                   80,96,83,91,99,76,89,94,87,92],

    "CGPA": [8.5,9.2,7.8,9.5,6.9,
             8.8,7.2,9.1,8.1,7.6,
             7.0,9.4,7.4,8.9,9.8,
             6.8,8.2,9.0,7.9,8.4],

    "City": ["Delhi","Lucknow","Noida","Jaipur","Delhi",
             "Noida","Lucknow","Delhi","Jaipur","Delhi",
             "Noida","Lucknow","Delhi","Jaipur","Delhi",
             "Noida","Lucknow","Delhi","Jaipur","Delhi"]
}

df = pd.DataFrame(data)

print(df)


In [ ]:
df.Age

In [ ]:
df.duplicated()

In [ ]:
df[df["City"]=="Delhi"]

In [ ]:
import numpy as np
array=np.array([10,20,30,40,50])
print(array)

[10 20 30 40 50]


In [ ]:
array=np.array([[10,20,30],[40,50,60]])
print(array)

[[10 20 30]
 [40 50 60]]


In [ ]:
array=np.array([[[10,20],[30,40]],[[50,60],[70,80]]])
print(array)


[[[10 20]
  [30 40]]

 [[50 60]
  [70 80]]]


In [ ]:
print(array.ndim)
print(array.shape)
print(a[0])

2
(2, 3)


NameError: name 'a' is not defined

In [ ]:
print(array.shape)
print(array.size)
print(array.dtype)

(2, 2, 2)
8
int64


In [ ]:
print(array[1,1,0])

70


In [ ]:
a=np.array([1,2,3,4,5])
b=np.array([6,7,8,9,10])
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[ 7  9 11 13 15]
[-5 -5 -5 -5 -5]
[ 6 14 24 36 50]
[0.16666667 0.28571429 0.375      0.44444444 0.5       ]


In [ ]:
print(a**2)

[ 1  4  9 16 25]


In [ ]:
print(np.sqrt(a))

[1.         1.41421356 1.73205081 2.         2.23606798]


In [ ]:
print(np.power(a,3))

[  1   8  27  64 125]


In [ ]:
print(np.mean(a))

3.0


In [ ]:
arr=np.array([1,2,3,4,5,6])
print(arr.reshape(2,3))

[[1 2 3]
 [4 5 6]]


In [ ]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr.T)

[[1 4]
 [2 5]
 [3 6]]


In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
plt.style.use('dark_background')

In [ ]:
df=pd.read_csv('/content/zomato.csv')
df.to_csv()

',url,address,name,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,approx_cost(for two people),reviews_list,menu_item,listed_in(type),listed_in(city)\n0,https://www.zomato.com/bangalore/jalsa-banashankari?context=eyJzZSI6eyJlIjpbNTg2OTQsIjE4Mzc1NDc0IiwiNTkwOTAiLCIxODM4Mjk0NCIsIjE4MjI0Njc2IiwiNTkyODkiLCIxODM3MzM4NiJdLCJ0IjoiUmVzdGF1cmFudHMgaW4gQmFuYXNoYW5rYXJpIHNlcnZpbmcgQnVmZmV0In19,"942, 21st Main Road, 2nd Stage, Banashankari, Bangalore",Jalsa,Yes,Yes,4.1/5,775.0,"080 42297555\r\n+91 9743772233",Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Lajawab, Tomato Shorba, Dum Biryani, Sweet Corn Soup","North Indian, Mughlai, Chinese",800,"[(\'Rated 4.0\', \'RATED\\n  A beautiful place to dine in.The interiors take you back to the Mughal era. The lightings are just perfect.We went there on the occasion of Christmas and so they had only limited items available. But the taste and service was not compromised at all.The only complaint is tha

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 391 entries, 0 to 390
Data columns (total 17 columns):
 #   Column                       Non-Null Count  Dtype  
---  ------                       --------------  -----  
 0   url                          391 non-null    object 
 1   address                      390 non-null    object 
 2   name                         390 non-null    object 
 3   online_order                 390 non-null    object 
 4   book_table                   390 non-null    object 
 5   rate                         355 non-null    object 
 6   votes                        390 non-null    float64
 7   phone                        386 non-null    object 
 8   location                     390 non-null    object 
 9   rest_type                    390 non-null    object 
 10  dish_liked                   182 non-null    object 
 11  cuisines                     390 non-null    object 
 12  approx_cost(for two people)  390 non-null    object 
 13  reviews_list        

In [ ]:
# Convert 'rate' column to numeric, handling '/5' and potential non-numeric values.
# First, convert to string type to ensure .str accessor works, then remove the '/5' suffix.
df['rate'] = df['rate'].astype(str).str.replace('/5', '', regex=False)

# Convert the cleaned string to numeric, coercing any errors (e.g., 'NEW' or empty strings) to NaN.
df['rate'] = pd.to_numeric(df['rate'], errors='coerce')

# Now, fill the NaN values with the mean of the numeric 'rate' column.
df['rate'].fillna(df['rate'].mean(), inplace=True)

# Check the null count to confirm the fix.
df['rate'].isnull().sum()

TypeError: can only concatenate str (not "int") to str

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 391 entries, 0 to 390
Data columns (total 17 columns):
 #   Column                       Non-Null Count  Dtype  
---  ------                       --------------  -----  
 0   url                          391 non-null    object 
 1   address                      390 non-null    object 
 2   name                         390 non-null    object 
 3   online_order                 390 non-null    object 
 4   book_table                   390 non-null    object 
 5   rate                         355 non-null    object 
 6   votes                        390 non-null    float64
 7   phone                        386 non-null    object 
 8   location                     390 non-null    object 
 9   rest_type                    390 non-null    object 
 10  dish_liked                   182 non-null    object 
 11  cuisines                     390 non-null    object 
 12  approx_cost(for two people)  390 non-null    object 
 13  reviews_list        

In [ ]:
df.dropna(inplace = True)
df.head()

,url,address,name,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,approx_cost(for two people),reviews_list,menu_item,listed_in(type),listed_in(city)
0,https://www.zomato.com/bangalore/jalsa-banasha...,"942, 21st Main Road, 2nd Stage, Banashankari, ...",Jalsa,Yes,Yes,4.1/5,775.0,080 42297555\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",800,"[('Rated 4.0', 'RATED\n A beautiful place to ...",[],Buffet,Banashankari
1,https://www.zomato.com/bangalore/spice-elephan...,"2nd Floor, 80 Feet Road, Near Big Bazaar, 6th ...",Spice Elephant,Yes,No,4.1/5,787.0,080 41714161,Banashankari,Casual Dining,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",800,"[('Rated 4.0', 'RATED\n Had been here for din...",[],Buffet,Banashankari
2,https://www.zomato.com/SanchurroBangalore?cont...,"1112, Next to KIMS Medical College, 17th Cross...",San Churro Cafe,Yes,No,3.8/5,918.0,+91 9663487993,Banashankari,"Cafe, Casual Dining","Churros, Cannelloni, Minestrone Soup, Hot Choc...","Cafe, Mexican, Italian",800,"[('Rated 3.0', ""RATED\n Ambience is not that ...",[],Buffet,Banashankari
3,https://www.zomato.com/bangalore/addhuri-udupi...,"1st Floor, Annakuteera, 3rd Stage, Banashankar...",Addhuri Udupi Bhojana,No,No,3.7/5,88.0,+91 9620009302,Banashankari,Quick Bites,Masala Dosa,"South Indian, North Indian",300,"[('Rated 4.0', ""RATED\n Great food and proper...",[],Buffet,Banashankari
4,https://www.zomato.com/bangalore/grand-village...,"10, 3rd Floor, Lakshmi Associates, Gandhi Baza...",Grand Village,No,No,3.8/5,166.0,+91 8026612447\r\n+91 9901210005,Basavanagudi,Casual Dining,"Panipuri, Gol Gappe","North Indian, Rajasthani",600,"[('Rated 4.0', 'RATED\n Very good restaurant ...",[],Buffet,Banashankari


In [ ]:
df.rename(columns = {'approx_cost(for two people)':'Cost2Plates', 'listed_in(type)':'Type'}, inplace = True)
df.head()

,url,address,name,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,Cost2Plates,reviews_list,menu_item,Type,listed_in(city)
0,https://www.zomato.com/bangalore/jalsa-banasha...,"942, 21st Main Road, 2nd Stage, Banashankari, ...",Jalsa,Yes,Yes,4.1/5,775.0,080 42297555\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",800,"[('Rated 4.0', 'RATED\n A beautiful place to ...",[],Buffet,Banashankari
1,https://www.zomato.com/bangalore/spice-elephan...,"2nd Floor, 80 Feet Road, Near Big Bazaar, 6th ...",Spice Elephant,Yes,No,4.1/5,787.0,080 41714161,Banashankari,Casual Dining,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",800,"[('Rated 4.0', 'RATED\n Had been here for din...",[],Buffet,Banashankari
2,https://www.zomato.com/SanchurroBangalore?cont...,"1112, Next to KIMS Medical College, 17th Cross...",San Churro Cafe,Yes,No,3.8/5,918.0,+91 9663487993,Banashankari,"Cafe, Casual Dining","Churros, Cannelloni, Minestrone Soup, Hot Choc...","Cafe, Mexican, Italian",800,"[('Rated 3.0', ""RATED\n Ambience is not that ...",[],Buffet,Banashankari
3,https://www.zomato.com/bangalore/addhuri-udupi...,"1st Floor, Annakuteera, 3rd Stage, Banashankar...",Addhuri Udupi Bhojana,No,No,3.7/5,88.0,+91 9620009302,Banashankari,Quick Bites,Masala Dosa,"South Indian, North Indian",300,"[('Rated 4.0', ""RATED\n Great food and proper...",[],Buffet,Banashankari
4,https://www.zomato.com/bangalore/grand-village...,"10, 3rd Floor, Lakshmi Associates, Gandhi Baza...",Grand Village,No,No,3.8/5,166.0,+91 8026612447\r\n+91 9901210005,Basavanagudi,Casual Dining,"Panipuri, Gol Gappe","North Indian, Rajasthani",600,"[('Rated 4.0', 'RATED\n Very good restaurant ...",[],Buffet,Banashankari


In [ ]:
df['location'].unique()

array(['Banashankari', 'Basavanagudi', 'Jayanagar', 'Kumaraswamy Layout',
       'Rajarajeshwari Nagar', 'Mysore Road', 'Uttarahalli',
       'South Bangalore'], dtype=object)

In [ ]:
df['Cost2Plates'].unique()

array(['800', '300', '600', '700', '550', '500', '450', '650', '400',
       '750', '200', '850', '1,200', '150', '350', '250', '1,500',
       '1,300', '1,000', '100', '900'], dtype=object)

In [ ]:
def handlecomma(value):
  value = str(value)
  if ',' in value:
    value=value.replace(',', '')
    return float(value)
  else:
    return float(value)

df['Cost2Plates'] = df['Cost2Plates'].apply(handlecomma)
df['Cost2Plates'].unique()

array([ 800.,  300.,  600.,  700.,  550.,  500.,  450.,  650.,  400.,
        750.,  200.,  850., 1200.,  150.,  350.,  250., 1500., 1300.,
       1000.,  100.,  900.])

In [ ]:
rest_types = df['rest_type'].value_counts(ascending = False)
rest_types

,count
rest_type,
Casual Dining,61
Quick Bites,57
Cafe,30
Dessert Parlor,7
Delivery,6
Beverage Shop,5
"Casual Dining, Cafe",4
"Quick Bites, Cafe",2
"Cafe, Casual Dining",2


In [ ]:
rest_types_lessthan1000 = rest_types[rest_types<1000]
rest_types_lessthan1000

,count
rest_type,
Casual Dining,61
Quick Bites,57
Cafe,30
Dessert Parlor,7
Delivery,6
Beverage Shop,5
"Casual Dining, Cafe",4
"Quick Bites, Cafe",2
"Cafe, Casual Dining",2


In [ ]:
import numpy as np
a=np.array([[[1,2],[2,3]],[[1,2],[7,8]]])
print(np.mean(a))
print(np.median(a))
print(np.std(a))

3.25
2.0
2.537222891273055


In [ ]:
import numpy as np
a=np.array([[1,2,3,4,5],[6,7,8,9,2]])
print(a.shape)

(2, 5)


In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import Lasso
from sklearn import metrics
plt.style.use('dark_background')

In [ ]:
car_dataset=pd.read_csv('/content/cars.csv')

In [ ]:
car_dataset.head(20)

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner
0,Maruti 800 AC,2007,60000,70000,Petrol,Individual,Manual,First Owner
1,Maruti Wagon R LXI Minor,2007,135000,50000,Petrol,Individual,Manual,First Owner
2,Hyundai Verna 1.6 SX,2012,600000,100000,Diesel,Individual,Manual,First Owner
3,Datsun RediGO T Option,2017,250000,46000,Petrol,Individual,Manual,First Owner
4,Honda Amaze VX i-DTEC,2014,450000,141000,Diesel,Individual,Manual,Second Owner
5,Maruti Alto LX BSIII,2007,140000,125000,Petrol,Individual,Manual,First Owner
6,Hyundai Xcent 1.2 Kappa S,2016,550000,25000,Petrol,Individual,Manual,First Owner
7,Tata Indigo Grand Petrol,2014,240000,60000,Petrol,Individual,Manual,Second Owner
8,Hyundai Creta 1.6 VTVT S,2015,850000,25000,Petrol,Individual,Manual,First Owner
9,Maruti Celerio Green VXI,2017,365000,78000,CNG,Individual,Manual,First Owner


In [ ]:
car_dataset.shape

(4340, 8)

In [ ]:
car_dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4340 entries, 0 to 4339
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype 
---  ------         --------------  ----- 
 0   name           4340 non-null   object
 1   year           4340 non-null   int64 
 2   selling_price  4340 non-null   int64 
 3   km_driven      4340 non-null   int64 
 4   fuel           4340 non-null   object
 5   seller_type    4340 non-null   object
 6   transmission   4340 non-null   object
 7   owner          4340 non-null   object
dtypes: int64(3), object(5)
memory usage: 271.4+ KB


In [ ]:
car_dataset.isnull().sum()

,0
name,0
year,0
selling_price,0
km_driven,0
fuel,0
seller_type,0
transmission,0
owner,0


In [ ]:
print(car_dataset.fuel.value_counts())
print(car_dataset.seller_type.value_counts())
print(car_dataset.transmission.value_counts())

fuel
Diesel      2153
Petrol      2123
CNG           40
LPG           23
Electric       1
Name: count, dtype: int64
seller_type
Individual          3244
Dealer               994
Trustmark Dealer     102
Name: count, dtype: int64
transmission
Manual       3892
Automatic     448
Name: count, dtype: int64
